
// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

export default defineConfig({
    schema: 'prisma/schema.prisma',
    migrations: {
        path: 'prisma/migrations',
    },
    datasource: {
        // Use DIRECT_URL for migrations (avoids PgBouncer prepared statement issues)
        // Adapting to check for NEXT_PUBLIC_ variants as well
        url: process.env['DIRECT_URL'] || process.env['NEXT_PUBLIC_DIRECT_URL'] || process.env['DATABASE_URL'] || process.env['NEXT_PUBLIC_DATABASE_URL'],
    },
});
